/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App.Main.NguoiDung;


import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.sql.Timestamp;
import javax.swing.JOptionPane;



/**
 *
 * @author WINDOWS
 */
public class DangKyPhong extends javax.swing.JFrame {

    /**
     * Creates new form DangKyPhong
     */
    
//    DecimalFormat formatter = new DecimalFormat("###,###,### VND");
//    UserEntity user = SessionManager.getSession().getUser();
//    UserEntity userSS = SessionManager.getSession().getUser();
//    static SessionDAO sessionDao = new SessionDAO();
//    
    public DangKyPhong() {
        initComponents();
        setLocationRelativeTo(null);
//        lblMaPhong.setText(TrangChuPanel.IdPhong);
//        showThongTin();
    }
    
//    public void showMaPhong(String maPhong) {
//        IdPhong = maPhong;
//        System.out.println(IdPhong);
//        lblMaPhong.setText(maPhong); // maPhongLabel là JLabel trên Frame 2 để hiển thị mã phòng
//    }
//    
//    public void showThongTin() {
//        try {
//            String query = "select GiaPhong from PhongTro where Id = ?;";
//            PreparedStatement ps = con.prepareStatement(query);
//            ps.setString(1, TrangChuPanel.IdPhong);
//            ResultSet rs = ps.executeQuery();
//            while(rs.next()) {
//                lblDatCoc.setText(formatter.format(rs.getFloat(1)));
//                lblGiaPhong.setText(formatter.format(rs.getFloat(1)));
//            }
//            
//            String query2 = "select * from DonGia_Config;";
//            PreparedStatement ps2 = con.prepareStatement(query2);
//            ResultSet rs2 = ps2.executeQuery();
//            while(rs2.next()) {
//                String key = rs2.getString("keyword");
//                float price = rs2.getFloat("value");
//                
//                if(key.equals("Giá điện")) {
//                    lblGiaDien.setText(formatter.format(price));
//                } else if (key.equals("Giá nước")) {
//                    lblGiaNuoc.setText(formatter.format(price));
//                } else if (key.equals("Giá internet")) {
//                    lblGiaInternet.setText(formatter.format(price));
//                } else if (key.equals("Giá rác")) {
//                    lblGiaRac.setText(formatter.format(price));
//                }
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }
//    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDatCoc = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblGiaPhong = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblGiaDien = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblGiaNuoc = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblGiaInternet = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblGiaRac = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ckbDongY = new javax.swing.JCheckBox();
        btnDatPhong = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        lblMaPhong = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(40, 46, 62));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 205, 31), 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ĐIỀU KHOẢN THUÊ NHÀ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Đặt cọc:");

        lblDatCoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDatCoc.setForeground(new java.awt.Color(255, 205, 31));
        lblDatCoc.setText("X, XXX, XXX VND");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Giá phòng:");

        lblGiaPhong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGiaPhong.setForeground(new java.awt.Color(255, 205, 31));
        lblGiaPhong.setText("X, XXX, XXX VND");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Giá điện:");

        lblGiaDien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGiaDien.setForeground(new java.awt.Color(255, 205, 31));
        lblGiaDien.setText("X, XXX, XXX VND");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Giá nước:");

        lblGiaNuoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGiaNuoc.setForeground(new java.awt.Color(255, 205, 31));
        lblGiaNuoc.setText("X, XXX, XXX VND");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Giá internet:");

        lblGiaInternet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGiaInternet.setForeground(new java.awt.Color(255, 205, 31));
        lblGiaInternet.setText("X, XXX, XXX VND");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Giá rác:");

        lblGiaRac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGiaRac.setForeground(new java.awt.Color(255, 205, 31));
        lblGiaRac.setText("X, XXX, XXX VND");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Quy định đóng tiền nhà: \n- Hóa đơn sẽ được thông báo qua ứng dụng và email. \n- Thời gian đóng từ ngày 05 đến ngày 10 hàng tháng.\n- Tiền nhà đóng bằng hình thức tiền mặt hoặc chuyển khoản.\n");
        jScrollPane1.setViewportView(jTextArea1);

        ckbDongY.setBackground(new java.awt.Color(40, 46, 62));
        ckbDongY.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbDongY.setForeground(new java.awt.Color(255, 255, 255));
        ckbDongY.setText("Tôi đồng ý");

        btnDatPhong.setBackground(new java.awt.Color(255, 205, 31));
        btnDatPhong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDatPhong.setForeground(new java.awt.Color(40, 46, 62));
        btnDatPhong.setText("Đặt phòng");
        btnDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatPhongActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Mã phòng:");

        lblMaPhong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaPhong.setForeground(new java.awt.Color(255, 205, 31));
        lblMaPhong.setText("X");

        jPanel2.setBackground(new java.awt.Color(46, 56, 86));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 205, 31)));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/houselogo.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("TRỌ VIỆT");

        btnThoat.setBackground(new java.awt.Color(255, 205, 31));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(40, 46, 62));
        btnThoat.setText("X");
        btnThoat.setPreferredSize(new java.awt.Dimension(38, 39));
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(199, 199, 199)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel16))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ckbDongY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDatPhong))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDatCoc))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblGiaDien))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(lblGiaInternet)))
                        .addGap(18, 57, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lblGiaPhong))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel12))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(lblGiaRac))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblGiaNuoc)))))))
                .addContainerGap(88, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(lblMaPhong)
                        .addGap(269, 269, 269))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(203, 203, 203))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblMaPhong))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblDatCoc)
                    .addComponent(jLabel4)
                    .addComponent(lblGiaPhong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblGiaDien)
                    .addComponent(jLabel8)
                    .addComponent(lblGiaNuoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblGiaInternet)
                    .addComponent(jLabel12)
                    .addComponent(lblGiaRac))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbDongY)
                    .addComponent(btnDatPhong))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatPhongActionPerformed
        // TODO add your handling code here:
//        if (ckbDongY.isSelected()) {
//            try {
//                long idPhong = Long.parseLong(lblMaPhong.getText());
//                long idNguoiDung = user.getId();
//                int ret = JOptionPane.showConfirmDialog(null, "Đăng ký phòng này?", "Thông báo", JOptionPane.YES_NO_OPTION);
//                if (ret == JOptionPane.NO_OPTION) {
//                    return;
//                }
//                PhongTroDAO ptDAO = new PhongTroDAO();
//                if (ptDAO.dangKyPhong(idNguoiDung, idPhong) == true) {
//                    JOptionPane.showMessageDialog(null, "Đăng ký phòng thành công! Vui lòng đợi, chủ trọ sẽ liên lạc sau!");
//                    this.dispose();
//                    return;
//                } else {
//                    JOptionPane.showMessageDialog(null, "Đăng ký phòng thất bại! Nếu bạn đã thuê phòng, có nhu cầu chuyển phòng hoặc có thắc mắc khác vui lòng liên hệ chủ trọ để nhận hỗ trợ! Cám ơn!");
//                }
//                SessionEntity ss = new SessionEntity();
//                ss.setUser(userSS);
//                ss.setMessage("Đăng ký phòng trọ");
//                ss.setStartTime(new Timestamp(System.currentTimeMillis()));
//                sessionDao.save(ss);
//                SessionEntity sss = sessionDao.getLast(userSS.getId());
//                setSession(sss);
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Vui lòng tích vào check box để đảm bảo đồng ý đặt phòng này!");
//            return;
//        }
    }//GEN-LAST:event_btnDatPhongActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DangKyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DangKyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DangKyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DangKyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DangKyPhong().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatPhong;
    private javax.swing.JButton btnThoat;
    private javax.swing.JCheckBox ckbDongY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblDatCoc;
    private javax.swing.JLabel lblGiaDien;
    private javax.swing.JLabel lblGiaInternet;
    private javax.swing.JLabel lblGiaNuoc;
    private javax.swing.JLabel lblGiaPhong;
    private javax.swing.JLabel lblGiaRac;
    private javax.swing.JLabel lblMaPhong;
    // End of variables declaration//GEN-END:variables
}
