/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package App.Main.NguoiDung;

import App.Utils.XAuth;
import App.Utils.XJdbc;
import App.Utils.XMail;

import javax.swing.*;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author PHONG
 */
public class DangKyPhongJDialog extends javax.swing.JDialog {
    // ====== dữ liệu truyền vào ======
    private String maPhong;
    private BigDecimal giaPhong;
    private BigDecimal donGiaDien;
    private BigDecimal donGiaNuoc;
    private int userId;
    private String userName;

    // ====== trạng thái kết quả ======
    private boolean accepted = false;

    public boolean isAccepted() { return accepted; }

    /**
     * Creates new form DangKyPhongJDialog
     */
    public DangKyPhongJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
                afterInit();
    }

    /** Constructor dùng trong flow: truyền đầy đủ dữ liệu */
    public DangKyPhongJDialog(java.awt.Frame parent, boolean modal,
                              String maPhong, BigDecimal giaPhong,
                              BigDecimal donGiaDien, BigDecimal donGiaNuoc,
                              int userId, String userName) {
        super(parent, modal);
        this.maPhong = maPhong;
        this.giaPhong = giaPhong;
        this.donGiaDien = donGiaDien;
        this.donGiaNuoc = donGiaNuoc;
        this.userId = userId;
        this.userName = userName;
        initComponents();
        afterInit();
        bindDataToUI();
    }

    // ====== helper format ======
    private static String fmtMoney(BigDecimal v) {
        if (v == null) return "0";
        NumberFormat nf = NumberFormat.getNumberInstance(new Locale("vi","VN"));
        nf.setMaximumFractionDigits(0);
        return nf.format(v);
    }

    private void afterInit() {
        setLocationRelativeTo(getOwner());
        // mặc định nút tắt
        btnDatPhong.setEnabled(false);
        ckbDongY.addActionListener(e -> btnDatPhong.setEnabled(ckbDongY.isSelected()));
    }

    private void bindDataToUI() {
        lblMaPhong.setText(maPhong != null ? maPhong : "X");
        lblGiaPhong.setText(giaPhong != null ? fmtMoney(giaPhong) + " VND" : "X, XXX, XXX VND");
        lblGiaDien.setText(donGiaDien != null ? fmtMoney(donGiaDien) + " /kWh" : "X, XXX, XXX VND");
        lblGiaNuoc.setText(donGiaNuoc != null ? fmtMoney(donGiaNuoc) + " /m³"  : "X, XXX, XXX VND");
    }
    
    // ==== THÊM 2 HÀM NÀY VÀO TRONG CLASS ====
private int effectiveUserId() {
    return (userId > 0) ? userId : (XAuth.user != null ? XAuth.user.getMaNguoiDung() : 0);
}

private String effectiveUserName() {
    return (userName != null && !userName.isBlank())
            ? userName
            : (XAuth.user != null ? XAuth.user.getHoTen() : "");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblGiaPhong = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblGiaDien = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblGiaNuoc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ckbDongY = new javax.swing.JCheckBox();
        btnDatPhong = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        lblMaPhong = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(40, 46, 62));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 205, 31), 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ĐIỀU KHOẢN THUÊ NHÀ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Giá phòng:");

        lblGiaPhong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGiaPhong.setForeground(new java.awt.Color(255, 205, 31));
        lblGiaPhong.setText("X, XXX, XXX VND");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Giá điện:");

        lblGiaDien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGiaDien.setForeground(new java.awt.Color(255, 205, 31));
        lblGiaDien.setText("X, XXX, XXX VND");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Giá nước:");

        lblGiaNuoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGiaNuoc.setForeground(new java.awt.Color(255, 205, 31));
        lblGiaNuoc.setText("X, XXX, XXX VND");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Quy định đóng tiền nhà: \n- Hóa đơn sẽ được thông báo qua ứng dụng và email. \n- Thời gian đóng từ ngày 05 đến ngày 10 hàng tháng.\n- Tiền nhà đóng bằng hình thức tiền mặt hoặc chuyển khoản.\n");
        jScrollPane1.setViewportView(jTextArea1);

        ckbDongY.setBackground(new java.awt.Color(40, 46, 62));
        ckbDongY.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbDongY.setForeground(new java.awt.Color(255, 255, 255));
        ckbDongY.setText("Tôi đồng ý");

        btnDatPhong.setBackground(new java.awt.Color(255, 205, 31));
        btnDatPhong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDatPhong.setForeground(new java.awt.Color(40, 46, 62));
        btnDatPhong.setText("Đặt phòng");
        btnDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatPhongActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Mã phòng:");

        lblMaPhong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaPhong.setForeground(new java.awt.Color(255, 205, 31));
        lblMaPhong.setText("X");

        jPanel2.setBackground(new java.awt.Color(46, 56, 86));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 205, 31)));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/houselogo.png"))); // NOI18N

        btnThoat.setBackground(new java.awt.Color(255, 205, 31));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(40, 46, 62));
        btnThoat.setText("X");
        btnThoat.setPreferredSize(new java.awt.Dimension(38, 39));
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel16))
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(353, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(lblMaPhong)
                        .addGap(269, 269, 269))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(203, 203, 203))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ckbDongY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(btnDatPhong))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblGiaDien))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                                .addComponent(lblGiaNuoc))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblGiaPhong)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblMaPhong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblGiaPhong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGiaDien)
                    .addComponent(jLabel6))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblGiaNuoc))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbDongY)
                    .addComponent(btnDatPhong))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatPhongActionPerformed
        // TODO add your handling code here:
    if (!ckbDongY.isSelected()) {
        JOptionPane.showMessageDialog(this, "Vui lòng tích vào 'Tôi đồng ý' trước khi đặt.");
        return;
    }

    int uid = effectiveUserId();           // <--- DÙNG uid
    String uname = effectiveUserName();    // <--- DÙNG uname
    if (uid <= 0) {
        JOptionPane.showMessageDialog(this, "Tài khoản không hợp lệ. Vui lòng đăng nhập lại.");
        return;
    }

    Connection con = null;
    try {
        // kiểm tra user hoạt động
        Integer okUser = XJdbc.getValue(
                "SELECT COUNT(*) FROM TaiKhoan WHERE MaNguoiDung = ? AND TrangThai = 1",
                uid); // <--- DÙNG uid
        if (okUser == null || okUser == 0) {
            JOptionPane.showMessageDialog(this, "Tài khoản không hợp lệ. Vui lòng đăng nhập lại.");
            return;
        }

        // kiểm tra phòng còn trống
        Integer okPhong = XJdbc.getValue(
                "SELECT COUNT(*) FROM Phong WHERE maPhong = ? AND trangThai = N'Trống'",
                maPhong);
        if (okPhong == null || okPhong == 0) {
            JOptionPane.showMessageDialog(this, "Phòng không còn trống.");
            return;
        }

        con = XJdbc.openConnection();
        con.setAutoCommit(false);

        String maHD = "HD" + java.time.LocalDateTime.now()
                .format(java.time.format.DateTimeFormatter.ofPattern("yyyyMMddHHmmss"));
        java.time.LocalDate start = java.time.LocalDate.now();
        java.time.LocalDate end   = start.plusMonths(6);

        // INSERT hợp đồng
        String sqlIns = """
            INSERT INTO HopDong(maHopDong, maNguoiDung, maPhong, ngayBatDau, ngayKetThuc)
            VALUES (?, ?, ?, ?, ?)
        """;
        XJdbc.executeUpdate(sqlIns, maHD, uid, maPhong, // <--- DÙNG uid
                java.sql.Date.valueOf(start), java.sql.Date.valueOf(end));

        // UPDATE phòng
        XJdbc.executeUpdate("UPDATE Phong SET trangThai = N'Đang thuê' WHERE maPhong = ?", maPhong);

        con.commit();

        accepted = true;
        JOptionPane.showMessageDialog(this, "Đặt phòng thành công!");

        // Gửi email (không làm fail giao dịch)
        try {
            final String ADMIN_EMAIL = "phonghuynh031226@gmail.com";
            String subject = "[NHÀ TRỌ] Đặt phòng mới: " + lblMaPhong.getText();
            String body =
                "Người dùng: " + uname + " (ID " + uid + ")\n" +
                "Phòng: " + lblMaPhong.getText() + "\n" +
                "Giá phòng: " + lblGiaPhong.getText() + "\n" +
                "Giá điện: " + lblGiaDien.getText() + "\n" +
                "Giá nước: " + lblGiaNuoc.getText() + "\n" +
                "Thời hạn hợp đồng: " + start + " → " + end;

            XMail.sendMail(ADMIN_EMAIL, subject, body); // dùng overload mới ở bước 1
        } catch (Exception mailEx) {
            mailEx.printStackTrace();
        }

        dispose();

    } catch (Exception ex) {
        try { if (con != null) con.rollback(); } catch (Exception ignore) {}
        JOptionPane.showMessageDialog(this, "Lỗi đặt phòng: " + ex.getMessage());
    } finally {
        try { if (con != null) con.setAutoCommit(true); } catch (Exception ignore) {}
    }
    }//GEN-LAST:event_btnDatPhongActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKyPhongJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKyPhongJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKyPhongJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKyPhongJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangKyPhongJDialog dialog = new DangKyPhongJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatPhong;
    private javax.swing.JButton btnThoat;
    private javax.swing.JCheckBox ckbDongY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblGiaDien;
    private javax.swing.JLabel lblGiaNuoc;
    private javax.swing.JLabel lblGiaPhong;
    private javax.swing.JLabel lblMaPhong;
    // End of variables declaration//GEN-END:variables
}
