/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package App.Main;

import App.DAO.TaiKhoanDAO;
import App.Entity.TaiKhoan;
import App.Impl.TaiKhoanDAOImpl;
import App.Utils.XAuth;
import App.Utils.XDialog;
import java.awt.Color;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

//import main.ui.quanlynhatro;
/**
 *
 * @author PHONG
 */
public class dangnhapJdialog extends javax.swing.JDialog implements dangnhapController{

    
private boolean dangNhapThanhCong = false;

    /**
     * Creates new form dangnhapJdialog
     */
    public dangnhapJdialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
                setUndecorated(true);  // Ẩn viền và nút X
        initComponents();
        open();
    }
    
        @Override 
public void open() { 
    this.setLocationRelativeTo(null); 
    
    // Lấy vùng màn hình usable (trừ taskbar)
    GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
    Rectangle usableBounds = env.getMaximumWindowBounds();

    // Thiết lập kích thước không che taskbar
    this.setBounds(usableBounds); // hoặc: this.setSize(usableBounds.width, usableBounds.height); this.setLocation(usableBounds.x, usableBounds.y);

    // Các thao tác khác nếu có...


} 
 

@Override
public void login() {
    String username = txtUsername.getText().trim();
    String password = new String(txtPassword.getPassword()).trim(); // lấy từ JPasswordField

    if (username.isEmpty() || password.isEmpty()) {
        XDialog.alert("Tên đăng nhập và mật khẩu không được để trống!");
        return;
    }

    TaiKhoanDAO dao = new TaiKhoanDAOImpl();
    TaiKhoan user;
    try {
        user = dao.findByTenTaiKhoanAndMatKhau(username, password);
    } catch (Exception ex) {
        ex.printStackTrace();
        XDialog.alert("Lỗi kết nối dữ liệu: " + ex.getMessage());
        return;
    }

    if (user == null) {
        XDialog.alert("Tên đăng nhập hoặc mật khẩu không đúng!");
        return;
    }

    // 0 = tạm khóa, 1 = hoạt động (theo Entity bạn đưa)
    if (user.getTrangThai() != null && user.getTrangThai() == 0) {
        XDialog.alert("Tài khoản đang bị tạm khóa!");
        return;
    }

    // Lưu user đăng nhập toàn cục
    XAuth.user = user;
    this.dangNhapThanhCong = true;

    // Đóng dialog đăng nhập
    this.dispose();

    // (Tuỳ chọn) đóng luôn màn hình TrangChuChung – nếu bạn muốn chuyển hẳn sang main tương ứng
    java.awt.Window owner = this.getOwner();
    if (owner != null) owner.dispose();

    // Mở màn hình chính theo vai trò
    javax.swing.SwingUtilities.invokeLater(() -> {
        try {
            if (Integer.valueOf(1).equals(user.getVaiTro())) {
                // Admin / Chủ trọ
                new App.Main.ChuTro.Main_ChuTro().setVisible(true);
            } else {
                // Người dùng / Người thuê
                            int userId   = user.getMaNguoiDung(); // <-- dùng getter đúng tên
            String hoTen = user.getHoTen();       // <-- dùng getter đúng tên
                new App.Main.NguoiDung.MainNguoiDung().setVisible(true);
            }
        } catch (Throwable t) {
            t.printStackTrace();
            XDialog.alert(null, "Không mở được màn hình chính: " + t.getMessage());
        }
    });
}

public boolean isDangNhapThanhCong() {

    return dangNhapThanhCong;

}









    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btndong = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        rememberMeCheckbox = new javax.swing.JCheckBox();
        btnDangNhap = new javax.swing.JButton();
        btnDangKy = new javax.swing.JButton();
        lblQuenMK = new javax.swing.JLabel();
        jTShow = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NHÀ TRỌ FPOLY");

        btndong.setBackground(new java.awt.Color(0, 0, 255));
        btndong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btndong.setForeground(new java.awt.Color(255, 255, 255));
        btndong.setText("X");
        btndong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndongActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/logo1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addGap(444, 444, 444)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 495, Short.MAX_VALUE)
                .addComponent(btndong, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(btndong, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 80));

        jLabel4.setBackground(new java.awt.Color(0, 0, 139));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel4.setText("ĐĂNG NHẬP");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 139));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Tên đăng nhập:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, 40));

        jLabel6.setBackground(new java.awt.Color(0, 0, 139));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Mật khẩu:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, -1, 40));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(40, 46, 62));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 240, 40));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(40, 46, 62));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, 190, 40));

        rememberMeCheckbox.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rememberMeCheckbox.setText("Remember Me");
        rememberMeCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rememberMeCheckboxActionPerformed(evt);
            }
        });
        getContentPane().add(rememberMeCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, -1));

        btnDangNhap.setBackground(new java.awt.Color(102, 204, 255));
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(40, 46, 62));
        btnDangNhap.setText("ĐĂNG NHẬP");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 180, 70));

        btnDangKy.setBackground(new java.awt.Color(102, 204, 255));
        btnDangKy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangKy.setForeground(new java.awt.Color(40, 46, 62));
        btnDangKy.setText("ĐĂNG KÝ ");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, 180, 70));

        lblQuenMK.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblQuenMK.setForeground(new java.awt.Color(100, 100, 100));
        lblQuenMK.setText("Quên mật khẩu?");
        lblQuenMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuenMKMouseClicked(evt);
            }
        });
        getContentPane().add(lblQuenMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 360, 180, -1));

        jTShow.setBackground(new java.awt.Color(153, 153, 255));
        jTShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/view.png"))); // NOI18N
        jTShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTShowMouseClicked(evt);
            }
        });
        jTShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTShowActionPerformed(evt);
            }
        });
        getContentPane().add(jTShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 310, 40, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/nen02.jpg"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(3000, 168));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rememberMeCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rememberMeCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rememberMeCheckboxActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:                                            
    login();



    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        // TODO add your handling code here:
        // Mở form đăng ký
        //dangkyJdialog dk = new dangkyJdialog((java.awt.Frame) getParent(), true);
//        dangkyJdialog dk = new dangkyJdialog((java.awt.Frame) null, true, this);
//        dk.setVisible(true);
    this.setVisible(false); // Ẩn form đăng nhập tạm thời
    java.awt.Window owner = javax.swing.SwingUtilities.getWindowAncestor(this);
    java.awt.Frame frame = (owner instanceof java.awt.Frame) ? (java.awt.Frame) owner : null;

    dangkyJdialog dk = new dangkyJdialog(frame, true); // <-- chỉ 2 tham số
    // nếu cần tham chiếu về form đăng nhập để callback:
    // dk.setLoginDialog(this);
    dk.setVisible(true);

    this.setVisible(true);  // hiện lại sau khi đóng đăng ký
        
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void lblQuenMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMKMouseClicked
        // TODO add your handling code here:
        quenmatkhauJdialog qmk = new quenmatkhauJdialog((java.awt.Frame) getParent(), true);
        qmk.setVisible(true);
    }//GEN-LAST:event_lblQuenMKMouseClicked

    private void jTShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTShowMouseClicked

        if (jTShow.isSelected()) {
            txtPassword.setEchoChar((char) 0);
            jTShow.setBackground(new Color(255, 205, 31));

            // Sử dụng getClass().getResource() với đường dẫn tương đối
            URL hideIconURL = getClass().getResource("src/main/resources/main/icon/hide.png");
            if (hideIconURL != null) {
                jTShow.setIcon(new ImageIcon(hideIconURL));
            } else {
                System.err.println("Hide icon not found.");
            }
        } else {
            txtPassword.setEchoChar('\u25cf');
            jTShow.setBackground(new Color(255, 205, 31));

            // Sử dụng getClass().getResource() với đường dẫn tương đối
            URL viewIconURL = getClass().getResource("src/main/resources/main/icon/view.png");
            if (viewIconURL != null) {
                jTShow.setIcon(new ImageIcon(viewIconURL));
            } else {
                System.err.println("View icon not found.");
            }
        }
    }//GEN-LAST:event_jTShowMouseClicked

    private void jTShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTShowActionPerformed

    private void btndongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndongActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn muốn đóng ứng dụng?", "Thoát?", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btndongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dangnhapJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dangnhapJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dangnhapJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dangnhapJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dangnhapJdialog dialog = new dangnhapJdialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btndong;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jTShow;
    private javax.swing.JLabel lblQuenMK;
    private javax.swing.JCheckBox rememberMeCheckbox;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
