/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App.Main;

import App.DAO.PhongDAO;
import App.Entity.Phong;
import App.Impl.PhongDAOImpl;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;

/**
 *
 * @author WINDOWS
 */
public class TrangChuChung extends javax.swing.JFrame implements TrangChuChungController{

    // ===== DAO & STATE =====
    private final PhongDAO phongDAO = new PhongDAOImpl();
    private DefaultTableModel model;

    public TrangChuChung() {
        initComponents();
        this.init(); 
    }
    
  @Override  
        public void init() {
        setLocationRelativeTo(null);
        wireMenus();
        initTable();

        // 1) Splash (xin chào)
        new xinchaoJdialog(this, true).setVisible(true);


        // 4) Tải dữ liệu phòng trống
        loadPhongTrong();
    }

    // ===== Menu click =====
    private void wireMenus() {
        jMenuTrangChu.addMouseListener(new MouseAdapter() {
            @Override public void mouseClicked(MouseEvent e) { loadPhongTrong(); }
        });
        jMenuThoat.addMouseListener(new MouseAdapter() {
            @Override public void mouseClicked(MouseEvent e) { thoat(); }
        });
    }

    // ===== Table =====
    private void initTable() {
        model = (DefaultTableModel) tblPhongTrong.getModel();
        model.setColumnIdentifiers(new Object[]{
                "Mã phòng", "Diện tích (m²)", "Giá phòng", "Địa chỉ", "Mô tả", "Liên hệ"
        });
        tblPhongTrong.setRowHeight(28);
    }

    private void loadPhongTrong() {
        model.setRowCount(0);
        try {
            List<Phong> list = phongDAO.findAll(); // nếu có findPhongTrong() thì gọi thẳng hàm đó

            for (Phong p : list) {
                // Chấp nhận 2 kiểu lưu trạng thái: "Trống" hoặc "0"
                String tt = nvl(p.getTrangThai()).trim();
                boolean isTrong = "trống".equalsIgnoreCase(tt) || "0".equals(tt);
                if (!isTrong) continue;

                model.addRow(new Object[]{
                        nvl(p.getMaPhong()),
                        fmtQty(p.getDienTich()),     // 21,5  |  20
                        fmtMoney(p.getGiaTien()),    // 2.500.000
                        nvl(p.getDiaChi()),
                        nvl(p.getMoTa()),
                        nvl(p.getLienHe())
                });
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi tải dữ liệu: " + ex.getMessage());
        }
    }

//    // ===== Menu actions =====
//    private void openDangNhap() {
//        try {
//            new dangnhapJdialog(this, true).setVisible(true); // đúng tên class bạn đang có
//        } catch (Throwable t) {
//            t.printStackTrace();
//            JOptionPane.showMessageDialog(this, "Không mở được Đăng nhập: " + t.getMessage());
//        }
//    }
//
//    private void openDangKy() {
//        try {
//            new dangkyJdialog(this, true).setVisible(true);
//        } catch (Throwable t) {
//            t.printStackTrace();
//            JOptionPane.showMessageDialog(this, "Không mở được Đăng ký: " + t.getMessage());
//        }
//    }

    private void thoat() {
        int c = JOptionPane.showConfirmDialog(this, "Bạn muốn thoát ứng dụng?", "Thoát",
                JOptionPane.YES_NO_OPTION);
        if (c == JOptionPane.YES_OPTION) System.exit(0);
    }

    // ===== Helpers =====
    private static String nvl(Object o) { return o == null ? "" : String.valueOf(o); }

    private static String fmtQty(BigDecimal v) {
        if (v == null) return "";
        NumberFormat nf = NumberFormat.getNumberInstance(new Locale("vi", "VN"));
        nf.setMaximumFractionDigits(2);   // diện tích có thể có .5, .25...
        nf.setMinimumFractionDigits(0);
        return nf.format(v);
    }

    private static String fmtMoney(BigDecimal v) {
        if (v == null) return "";
        NumberFormat nf = NumberFormat.getNumberInstance(new Locale("vi", "VN"));
        nf.setMaximumFractionDigits(0);   // tiền VND thường không lấy lẻ
        return nf.format(v);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhongTrong = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTrangChu = new javax.swing.JMenu();
        jMenuDangnhap = new javax.swing.JMenu();
        jMenuDangky = new javax.swing.JMenu();
        jMenuThoat = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(40, 46, 62));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 630));

        tblPhongTrong.setBackground(new java.awt.Color(207, 243, 243));
        tblPhongTrong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblPhongTrong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPhongTrong.setGridColor(new java.awt.Color(255, 255, 255));
        tblPhongTrong.setSelectionBackground(new java.awt.Color(40, 46, 62));
        tblPhongTrong.setSelectionForeground(new java.awt.Color(255, 205, 31));
        tblPhongTrong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhongTrongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhongTrong);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 205, 31));
        jLabel2.setText("DANH SÁCH PHÒNG TRỐNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jLabel2)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(46, 56, 86));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 205, 31), 2));
        jMenuBar1.setForeground(new java.awt.Color(40, 46, 62));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(615, 70));

        jMenuTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        jMenuTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/home (1).png"))); // NOI18N
        jMenuTrangChu.setText("Trang chủ");
        jMenuTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuBar1.add(jMenuTrangChu);

        jMenuDangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/Unknown person.png"))); // NOI18N
        jMenuDangnhap.setText("Đăng nhập");
        jMenuDangnhap.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuDangnhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuDangnhapMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuDangnhap);

        jMenuDangky.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/edit.png"))); // NOI18N
        jMenuDangky.setText("Đăng ký");
        jMenuDangky.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuDangky.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuDangkyMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuDangky);

        jMenuThoat.setForeground(new java.awt.Color(255, 255, 255));
        jMenuThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/logout.png"))); // NOI18N
        jMenuThoat.setText("Thoát");
        jMenuThoat.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuThoatMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuThoat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuThoatMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuThoatMouseClicked

    private void tblPhongTrongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhongTrongMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblPhongTrongMouseClicked

    private void jMenuDangnhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuDangnhapMouseClicked
        // TODO add your handling code here: 
        this.showdangnhapJDialog(this); 
    }//GEN-LAST:event_jMenuDangnhapMouseClicked

    private void jMenuDangkyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuDangkyMouseClicked
        // TODO add your handling code here:
         this.showdangkyJDialog(this); 
    }//GEN-LAST:event_jMenuDangkyMouseClicked

    /**
     * @param args the command line arguments
     */
public static void main(String[] args) {
    // Thử Nimbus, nếu không có thì giữ LAF mặc định
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ignore) { /* dùng LAF mặc định */ }

    java.awt.EventQueue.invokeLater(() -> {
        try {
            new TrangChuChung().setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace(); // để thấy lỗi thật trong Output
            javax.swing.JOptionPane.showMessageDialog(
                null, "Lỗi khởi động: " + ex.getClass().getSimpleName() + " - " + ex.getMessage()
            );
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDangky;
    private javax.swing.JMenu jMenuDangnhap;
    private javax.swing.JMenu jMenuThoat;
    private javax.swing.JMenu jMenuTrangChu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPhongTrong;
    // End of variables declaration//GEN-END:variables

}
